### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by haesleinhuepf** [kreshuklab/go-nuclear#1]
Hi @qin-yu ,

that's a fantastic tool, thanks for sharing! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by akreshuk** [comment]
thanks for noticing this oversight, @haesleinhuepf ! We'll add one asap.

**Comment by qin-yu** [comment]
Hi @haesleinhuepf, thank you for the issue. I added an MIT License for this repo

**Comment by haesleinhuepf** [comment]
Awesome, thanks for the quick response!
